### ISSUE TITLE
Invalid comparison operator in dependency: >=

### ISSUE THREAD

**Issue by pierucci** [hadley/devtools#1247]
Builds on Travis are [now failing](https://travis-ci.org/pierucci/heemod/builds/141599194) with the following error that seems to come from `devtools`:

```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = TRUE);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
trying URL 'https://cloud.r-project.org/src/contrib/diagram_1.6.3.tar.gz'
Content type 'application/x-gzip' length 466691 bytes (455 KB)
==================================================
downloaded 455 KB
Installing diagram
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >= 
Calls: <Anonymous> ... install -> install_deps -> dev_package_deps -> lapply -> FUN
Execution halted
```

I did not change the DESCRIPTION file. I do not understand the cause of the error because if I read `package-deps.r` line 34 I can see the `>=` operator listed:

``` r
compare_nna %in% c(">", ">=", "==", "<=", "<")
```

**Comment by HenrikBengtsson** [comment]
I'm coming here because I'm seeing the same for the [caper](https://cran.r-project.org/web/packages/caper/) CRAN package.  In this case it's because there's an extra space after the parentheses holding the version specification;

```r
> devtools:::parse_deps("R (>= 2.10), ape (>= 3.0-6) , MASS, mvtnorm")
Error in devtools:::parse_deps("R (>= 2.10), ape (>= 3.0-6) , MASS, mvtnorm") : 
  Invalid comparison operator in dependency: >= 
```
It'll work if one removes that extra space after the "ape" spec;
```r
> devtools:::parse_deps("R (>= 2.10), ape (>= 3.0-6), MASS, mvtnorm")
     name compare version
2     ape      >=   3.0-6
3    MASS    <NA>    <NA>
4 mvtnorm    <NA>    <NA>
```

Looking at the [diagram](https://cran.r-project.org/web/packages/diagram/) package, you'll find the same extra space in the DESCRIPTION:
```r
Depends:	R (≥ 2.01) , shape
```

So, this sounds like an issue with `devtools:::parse_deps()`.   This easiest fix is probably to [replace](https://github.com/hadley/devtools/blob/b6a23be508043fd0ffc24316034b5e45bfc1a941/R/package-deps.r#L18):
```r
  pieces <- strsplit(string, ",")[[1]]
```
with
```r
  pieces <- strsplit(string, "[ ]*,[ ]*")[[1]]
```
such that we get:
```r
> string <- "R (>= 2.10), ape (>= 3.0-6) , MASS, mvtnorm"
> strsplit(string, "[ ]*,[ ]*")[[1]]
[1] "R (>= 2.10)"    "ape (>= 3.0-6)" "MASS"           "mvtnorm"       
```
instead of
```r
> strsplit(string, ",")[[1]]
[1] "R (>= 2.10)"      " ape (>= 3.0-6) " " MASS"            " mvtnorm"        
```

**Comment by HenrikBengtsson** [comment]
@hadley, forgot to say, if you don't mind `sQuote()`, the error message would have been more informative with quotes, i.e.
```r
  if(!all(compare_valid)) {
    stop("Invalid comparison operator in dependency: ",
      paste(sQuote(compare_nna[!compare_valid]), collapse = ", "))
  }
```

**Comment by HenrikBengtsson** [comment]
@pierucci, the following patched version should fix it for you until fixed upstream:
```r
devtools::install_github("HenrikBengtsson/devtools@hotfix/parse_deps")
```

**Comment by pierucci** [comment]
@HenrikBengtsson Thanks! The issue was fixed by applying your patch in the Travis-CI config file (efd96f1f1bd285c8687dd8a24237197980db4d36).

**Comment by hadley** [comment]
Is this still a problem?

**Comment by jannepeltola** [comment]
It's still a problem for me with `devtools::install_github("google/CausalImpact")` (or, more specifically, `BoomSpikeSlab` 0.7.0):

```
Downloading GitHub repo google/CausalImpact@master
from URL https://api.github.com/repos/google/CausalImpact/zipball/master
Installing CausalImpact
trying URL 'https://cran.rstudio.com/src/contrib/bsts_0.6.5.tar.gz'
Content type 'application/x-gzip' length 149015 bytes (145 KB)
==================================================
downloaded 145 KB

tar: Failed to set default locale
tar: Failed to set default locale
Installing bsts
trying URL 'https://cran.rstudio.com/src/contrib/BoomSpikeSlab_0.7.0.tar.gz'
Content type 'application/x-gzip' length 70988 bytes (69 KB)
==================================================
downloaded 69 KB

tar: Failed to set default locale
tar: Failed to set default locale
Installing BoomSpikeSlab
Error in FUN(X[[i]], ...) : 
  Invalid comparison operator in dependency: >=
```

I was running the most recent version of `devtools`. 

Installing the @HenrikBengtsson patch fixed the problem for me, but it would be good to have the fix upstream as well.

**Comment by jimhester** [comment]
The patch has been merged to master, but people still run into it if they are using the CRAN release though (such as is the default on travis).

**Comment by dweichel** [comment]
@jimhester I'm running into the same issue as @jannepeltola. How should I proceed if I'm using a CRAN release 3.3.3?

**Comment by sconti555** [comment]
@jimhester Same thing here: I'm running into the exact same problem as @dweichel and @jannepeltola and seem to be able to successfully install neither the @HenrikBengtsson devtools patch (file no longer there) nor the fork (due to "invalid package" warnings followed by "no packages" specified errors).

**Comment by zezantam** [comment]
@jimhester same here - same issue as @dweichel and @jannepeltola and @HenrikBengtsson is not available

**Comment by HenrikBengtsson** [comment]
I removed my hotfix after my fix (https://github.com/hadley/devtools/pull/1257) was merged into the master branch.  

@zezantam, @dweichel and @jannepeltola, what version are you using?  The one on CRAN or the one on the `master` branch?  The devtools 1.12.0 (2016-12-05) available on CRAN does _not_ to contain the fix (see below).

Retry with installing devtools on the master branch, i.e.
```r
devtools::install_github("hadley/devtools")
```
 
# Details
What the devtools 1.12.0 implements:
```r
> packageVersion("devtools")
[1] '1.12.0'
> devtools::parse_deps 
function (string) 
{
    if (is.null(string)) 
        return()
    stopifnot(is.character(string), length(string) == 1)
    if (grepl("^\\s*$", string)) 
        return()
    pieces <- strsplit(string, ",")[[1]]
[...]
```
Compare that `pieces <- ...` line to what devtools 1.12.0-9000 (master branch) has:
```r
> packageVersion("devtools")
[1] '1.12.0.9000'
>  devtools::parse_deps 
function (string) 
{
    if (is.null(string)) 
        return()
    stopifnot(is.character(string), length(string) == 1)
    if (grepl("^\\s*$", string)) 
        return()
    pieces <- strsplit(string, "[[:space:]]*,[[:space:]]*")[[1]]
```
If you don't see the latter, that's why.

**Comment by zezantam** [comment]
thanks for such a quick reply @HenrikBengtsson - I solved it by running `install.packages("BoomSpikeSlab")` 
before running 
`devtools::install_github("google/CausalImpact")`
which probably effectively did the same thing as you suggested

**Comment by sconti555** [comment]
I followed the same approach @zezantam adopted -- with the CRAN-sourced 'devtools' (version 1.12.0) pre-installed -- and it worked for me as well.  Sincere thanks to you all for chipping in!
