### ISSUE TITLE
devtools::install() fails when path to Windows source directory contains an ampersand ("&").

### ISSUE THREAD

**Issue by JoshOBrien** [hadley/devtools#715]
At least this is the case on my Windows 7 box, running `R version 3.1.2` and `devtools_1.7.0`.

An example to (hopefully) reproduce the issue I'm reporting:

    setwd("/")
    dir.create("A & B")
    setwd("A & B")
    ## Create a source directory
    library(pkgKitten)
    kitten("aPackage")
    ## Now try to install()
    library(devtools)
    install("aPackage")
    # Installing aPackage
    # "C:/R/R-current/bin/x64/R" --vanilla CMD INSTALL "C:/A & B/aPackage"  \
    #   --library="C:/R/Library" --install-tests 
    # 
    # Warning: invalid package 'C:/A'
    # Error: ERROR: no packages specified
    # 'B' is not recognized as an internal or external command,
    # operable program or batch file.
    # Error: Command failed (1)

**Comment by wch** [comment]
I think this may already be fixed in the latest dev version of devtools.

**Comment by JoshOBrien** [comment]
OK. I just updated using `build_github_devtools()` etc., giving me `devtools_1.7.0.9000`, and I still get the error. Not sure, though, whether you're referring to another even later latest dev version. Thanks.

**Comment by wch** [comment]
That is the right version - I thought it might have been fixed along with #676, but apparently not.

I think in addition to the `normalizePath` that was added, it might also need `shQuote`.

**Comment by JoshOBrien** [comment]
Hi Winston,

That would've been my first thought too, but it `install()` already performs the requisite call to `shQuote()`.

Trying an idea I found in [this SO answer](http://stackoverflow.com/a/18518748/980833) (which recommends prepending ampersands in paths with the caret symbol, so `&` becomes `^&`, I found that the following addition to the body of install actually makes it work -- at least in this single test case:

    built_path <- normalizePath(built_path, winslash = "/")
    ## <BEGIN added code>
    if(Sys.info()[["sysname"]]=="Windows") {
        built_path <- gsub("&", "^&", built_path)
    }
    ## <END added code>
    R(paste("CMD INSTALL ", shQuote(built_path), " ", opts, sep = ""),
        quiet = quiet)

Feels like there must be a better way (and if there isn't, there should be one built into base R), but this does seem to do the trick.

**Comment by hadley** [comment]
@jjallaire any thoughts?

**Comment by jjallaire** [comment]
This may it may or not be an Rcpp issue (Kevin would know for sure) but I
don't know when our next release is so I'd recommend a local workaround for
now

On Apr 21, 2015, at 10:27 AM, Hadley Wickham <notifications@github.com>
wrote:

@jjallaire <https://github.com/jjallaire> any thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/hadley/devtools/issues/715#issuecomment-94813832>.

**Comment by hadley** [comment]
@jjallaire I was wondering more if you're aware of this issue of specially escaping `&` in quoted paths on windows?

**Comment by JoshOBrien** [comment]
@hadley It looks like it's a Windows command shell issue that comes into play whenever passing arguments that contain ampersands, pipes, or parentheses. There's a mention of it [here](http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true) in the official Microsoft documentation (search for "the ampersand"), and [here](http://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files) is a related and highly upvoted SO answer

**Comment by hadley** [comment]
@JoshOBrien it's not obvious those links apply here - I'm not using the command shell and I'm already quoting the paths.

**Comment by hadley** [comment]
I don't think this is a devtools issue. If I run the following code from the command line, I also get an error:

```
mkdir "A&"
R
# install.packages("pkgKitten")
pkgKitten::kitten("aPackage", "A&")
q()
R CMD INSTALL "A&"
```

I'm going to report to R-devel.

**Comment by rBatt** [comment]
Working on a Windows machine recently (usually on Mac), just ran into this issue for the first time. @hadley , was there any useful response to your R-devel report? Any suggestion where I can go to look for a solution to this issue? Thanks
